### ISSUE TITLE
Check if the directory has an extension

### ISSUE THREAD

**Issue by DevD4v3** [ose-net/yesql.net#43]
`LoadFromDirectories` does not check if the directory passed as argument has an extension:
```cs
var data = new YeSqlLoader().LoadFromDirectories("sample.sql");
```

### Expected behavior
It should generate the following error: 
```sh
Unhandled exception. YeSql.Net.YeSqlLoaderException: error: 'sample.sql' must not have an extension.
```

### Current behavior
```sh
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\syslan\Documents\Visual Studio 2022\yesql.net\samples\LoaderSample\sample.sql'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at YeSql.Net.YeSqlLoader.GetSqlFilesDetails(String directoryName)+MoveNext() in C:\Users\syslan\Documents\Visual Studio 2022\yesql.net\src\Loader\YeSqlLoader.HelperMethods.cs:line 78
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at YeSql.Net.EnumerableExtensions.IsEmpty[T](IEnumerable`1 source) in C:\Users\syslan\Documents\Visual Studio 2022\yesql.net\src\Extensions\EnumerableExtensions.cs:line 15
   at YeSql.Net.YeSqlLoader.LoadFromDirectory(String directoryName) in C:\Users\syslan\Documents\Visual Studio 2022\yesql.net\src\Loader\YeSqlLoader.cs:line 74
   at YeSql.Net.YeSqlLoader.LoadFromDirectories(String[] directories) in C:\Users\syslan\Documents\Visual Studio 2022\yesql.net\src\Loader\YeSqlLoader.cs:line 55
   at Program.<Main>$(String[] args) in C:\Users\syslan\Documents\Visual Studio 2022\yesql.net\samples\LoaderSample\Program.cs:line 5
```

**Comment by DevD4v3** [comment]
This issue will not be completed because it may introduce new problems.

For example, these directories are valid:
- net7.0
- Viamatica S.A
- IGDv2.0

If this issue is implemented, the loader will take those directories with extension and throw an error.

Methods like `Path.HasExtension` or `Path.GetExtension` simply do not work in these cases:
```cs
Console.WriteLine(Path.HasExtension("net7.0"));
Console.WriteLine(Path.GetExtension("net7.0")); 
/*
   Output:
   True
   .0
*/
```
